
all : microworld2

microworld2:  pendulum.c ../utils.c ../brains/brain.c  ../learning.c ../analysis.c ../cJSON/cJSON.c 
	 g++  pendulum.c  ../utils.c ../brains/brain.c ../learning.c  ../analysis.c ../cJSON/cJSON.c -o microworld2 -g -lm


