
all : microworld1

microworld1: avoidance.c hunter.c movement.c world.c agent.c m1analysis.c ../brains/brain.c ../utils.c ../learning.c ../analysis.c ../cJSON/cJSON.c
	 g++ avoidance.c hunter.c movement.c world.c agent.c m1analysis.c ../brains/brain.c ../utils.c ../learning.c ../analysis.c ../cJSON/cJSON.c -o microworld1 -g -lm

