
all : microworld1

microworld1: avoidance.c hunter.c movement.c world.c agent.c ../brain.c ../utils.c ../learning.c ../analysis.c 
	 gcc avoidance.c hunter.c movement.c world.c agent.c ../brain.c ../utils.c ../learning.c ../analysis.c -o microworld1 -g -lm

