
all : microworld2

microworld2: pendulum.c  ../brain.c ../utils.c ../learning.c ../analysis.c ../cJSON/cJSON.c 
	 gcc pendulum.c ../brain.c ../utils.c ../learning.c ../analysis.c ../cJSON/cJSON.c -o microworld2 -g -lm


