
all : microworld2

microworld2:  pendulum.c ../utils.c ../brain.c  ../learning.c ../analysis.c ../cJSON/cJSON.c 
	 gcc  pendulum.c  ../utils.c ../brain.c ../learning.c  ../analysis.c ../cJSON/cJSON.c -o microworld2 -g -lm


